name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          # Parts of this package depend on Pkg internals.
          # Because Pkg internals are allowed to change between Julia minor versions,
          # we should run CI on each minor version of Julia that we want to support.
          # But it's fine to just run these with Linux, as not to make the matrix too
          # big. Also, Julia 1.4.2 does not work on the macos-latest runner for some
          # reason, failing with a linking error, so that also sidesteps that issue.
          - '1.3'
          - '1.4'
          - '1.5'
          - '1.6'
          - '1.7'
          - '1.8'
          - '1.9'
          - '1.10'
          - '1' # automatically expands to the latest stable 1.x release
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        # We still want to run CI on Windows and MacOS for some Julia versions, so
        # so doing that for nightly and the latest release.
        include:
          - os: macOS-latest
            version: '1'
            arch: x64
          - os: windows-latest
            version: '1'
            arch: x64
          - os: macOS-latest
            version: 'nightly'
            arch: x64
          - os: windows-latest
            version: 'nightly'
            arch: x64
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
